package com.tk_lab.demo.entity;

public class DemoTable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.id
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.name
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.password
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.sex
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.age
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    private Integer age;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.mail
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    private String mail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.address
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.id
     * @return  the value of demo_table.id
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.id
     * @param id  the value for demo_table.id
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.name
     * @return  the value of demo_table.name
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.name
     * @param name  the value for demo_table.name
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.password
     * @return  the value of demo_table.password
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.password
     * @param password  the value for demo_table.password
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.sex
     * @return  the value of demo_table.sex
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.sex
     * @param sex  the value for demo_table.sex
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.age
     * @return  the value of demo_table.age
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.age
     * @param age  the value for demo_table.age
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.mail
     * @return  the value of demo_table.mail
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.mail
     * @param mail  the value for demo_table.mail
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.address
     * @return  the value of demo_table.address
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.address
     * @param address  the value for demo_table.address
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }
}