package com.tk_lab.demo.entity;

public class DemoTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.id
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.name
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.password
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    private Integer password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.df_start_time
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    private String dfStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.df_end_time
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    private String dfEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.id
     *
     * @return the value of demo_table.id
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.id
     *
     * @param id the value for demo_table.id
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.name
     *
     * @return the value of demo_table.name
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.name
     *
     * @param name the value for demo_table.name
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.password
     *
     * @return the value of demo_table.password
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public Integer getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.password
     *
     * @param password the value for demo_table.password
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public void setPassword(Integer password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.df_start_time
     *
     * @return the value of demo_table.df_start_time
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public String getDfStartTime() {
        return dfStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.df_start_time
     *
     * @param dfStartTime the value for demo_table.df_start_time
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public void setDfStartTime(String dfStartTime) {
        this.dfStartTime = dfStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.df_end_time
     *
     * @return the value of demo_table.df_end_time
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public String getDfEndTime() {
        return dfEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.df_end_time
     *
     * @param dfEndTime the value for demo_table.df_end_time
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    public void setDfEndTime(String dfEndTime) {
        this.dfEndTime = dfEndTime;
    }
}