package com.tk_lab.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tk_lab.demo.entity.DemoTable;

public interface DemoTableMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo_table
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo_table
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    int insert(DemoTable record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo_table
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    DemoTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo_table
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    List<DemoTable> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo_table
     * @mbg.generated  Sun Mar 06 20:43:31 JST 2022
     */
    int updateByPrimaryKey(DemoTable record);

    /**
     * id と password をもとにユーザーデータを取得する。<br>
     * ※SQL インジェクション対策を行っていない。<br>
     * @param id
     * @param password
     * @return ユーザーデータ
     */
    DemoTable selectUserDataVerNoGuardSQLInjection(@Param("id") String id, @Param("password") String password);
}