package com.tk_lab.demo.mapper;

import com.tk_lab.demo.entity.DemoTable;
import java.util.List;

public interface DemoTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    int insert(DemoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    DemoTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    List<DemoTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated Sun Mar 06 00:16:31 JST 2022
     */
    int updateByPrimaryKey(DemoTable record);
}